steps:
  - label: "build_app" 
    commands:
      - "cd hello"
      - "go build"
    artifact_paths: "hello/hello"
    plugins:
      - docker#v5.12.0:
          image: "golang:1.18.0"
  - label: "Prompt for user's name before executing"
    key: "user_input"
    input: "Prompt for details"
    fields:
    - text: "What shall I call you today?"
      key: "my-name"
  - label: "run_app"
    depends_on: "user_input"
    commands: 
    - "buildkite-agent artifact download hello/hello . --step build_app"
    - "chmod +x hello/hello"
    - "NAME=$(buildkite-agent meta-data get my-name)"
    - "./hello/hello $$NAME"
