agents:
  queue: "default"

steps:
  - label: "build_app"
    command: "go build -o dist/hello ."
    artifact_paths: "./dist/hello"
    plugins:
      - docker:
          image: "golang:1.18.0"
  - block: "Continue?"
  - command: "buildkite-agent artifact download dist/hello hello/hello --step build_app; chmod +x hello/hello; hello/hello $$BUILDKITE_BUILD_AUTHOR"



