steps:
  - label: "Build Application"
    key: "build_app"
    commands:
      - "cd hello"
      - "go build"
    # being able to set a working directory here would be good, scoped to the block?
    artifact_paths: "hello/hello"
    plugins:
      - docker#v5.12.0:
          image: "golang:1.18.0"
  - label: "Prompt for user's name before executing"
    key: "user_input"
    input: "Prompt for details"
    fields:
    - text: "What shall I call you today?"
      key: "my-name"
  - label: "Run Application after User Input"
    key: "run_app"
    # having to explicitly set this is not intuitive, perhaps a configuration for "block_until_input: true on the input field?"    
    depends_on: "user_input"
    commands: 
    # could this have a convention associated with it like BUILDKITE_INPUT_XXXX rather than an expicit call?
    - "NAME=$(buildkite-agent meta-data get my-name)"
    - "buildkite-agent artifact download hello/hello . --step build_app"
    - "chmod +x hello/hello"
    - "./hello/hello $$NAME"

