steps:
  - label: "build_app" 
    commands:
      - "cd hello"
      - "go build"
    artifact_paths: "hello/hello"
    plugins:
      - docker#v5.12.0:
          image: "golang:1.18.0"
  - block: "Continue?"
  - commands: 
    - "buildkite-agent artifact download hello/hello . --step build_app"
    - "chmod +x hello/hello"
    - "./hello/hello $BUILDKITE_BUILD_AUTHOR"
