agents:
  queue: "default"

steps:
  - command: "go build -o dist/hello ."
    key: "build_app"
    artifact_paths: "./dist/hello"
    plugins:
      - docker:
          image: "golang:1.18.0"
  - block: "Continue?"
  - commands: 
    - "buildkite-agent artifact download dist/hello ./hello/hello --step build_app"
    - "chmod +x ./hello/hello"
    - "./hello/hello $$BUILDKITE_BUILD_AUTHOR"



